---
- name: "Execute eks post cluster creation steps"
  hosts: localhost
  ignore_errors: no
  vars:
    cluster_arn: "{{ eks_cluster_arn }}"
    cluster_endpoint: "{{ eks_cluster_endpoint }}"
    cluster_name: "{{ eks_cluster_name }}"
    cluster_ca_data: "{{ eks_cluster_ca }}"
    kms_key_arn: "{{ kms_key_arn }}"
    region: "{{ region }}"
  tasks:
    - name: create .kube folder under home dir
      file:
        path: ~/.kube
        state: directory
    - name: Generate kubeconfig file
      template:
        src: ./kubeconfig.j2
        dest: ~/.kube/config
    - name: "set context"
      command: "kubectl config use-context {{ eks_cluster_arn }}"
    - name: "Remove default storage class annotation for GP2"
      command: kubectl annotate sc gp2 storageclass.kubernetes.io/is-default-class-
    - name: Generate gp3 storage class manifest
      template:
        src: ./sc-gp3.j2
        dest: ./sc-gp3.yaml
    - name: "Deploy gp3 storage class"
      command: kubectl -n kube-system apply -f ./sc-gp3.yaml
